config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :admins
  devise_for :users


  resources :users
  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]

  namespace :admin do
    resources :users
    root 'users#index'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'base#index'
end

app/models/conversation.rb
# == Schema Information
#
# Table name: conversations
#
#  id          :integer          not null, primary key
#  author_id   :integer
#  receiver_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Conversation < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
  has_many :personal_messages, -> { order(created_at: :asc) }, dependent: :destroy

  validates :author, uniqueness: { scope: :receiver }

  scope :participating, -> (user) do
    where("(conversations.author_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
  end

  scope :between, -> (sender_id, receiver_id) do
    where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id)).limit(1)
  end

  def with(current_user)
    author == current_user ? receiver : author
  end

  def participates?(user)
    author == user || receiver == user
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < BaseController
  before_action :set_conversation, except: [:index]
  before_action :check_participating!, except: [:index]

  def index
    @conversations = Conversation.participating(current_user).order('updated_at DESC')
  end

  def show
    @personal_message = PersonalMessage.new
  end

  def new
    redirect_to conversation_path(@conversation) and return if @conversation
    @personal_message = current_user.personal_messages.build
  end

  private

  def find_conversation!
    if params[:receiver_id]
      @receiver = User.find_by(id: params[:receiver_id])
      redirect_to(root_path) and return unless @receiver
      @conversation = Conversation.between(current_user.id, @receiver.id)[0]
    else
      @conversation = Conversation.find_by(id: params[:conversation_id])
      redirect_to(root_path) and return unless @conversation && @conversation.participates?(current_user)
    end
  end

  def set_conversation
    @conversation = Conversation.find_by(id: params[:id])
  end

  def check_participating!
    redirect_to root_path unless @conversation && @conversation.participates?(current_user)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  # def count_messages(conversation)
  #   @count = conversation
  #   if @count > 0
  #     flash[:success] = "You have a #{@count} messages"
  #   else
  #     flash[:success] = "You have a 0 messages"
  #   end
  # end
end

app/views/conversations/_conversation.html.slim
.card
  .card-header
    .card-title
      h3=conversation.with(current_user).name
  .card-body
    p=conversation.personal_messages.last.body.truncate(50)
    p
      =link_to 'View conversation', conversation_path(conversation), type: 'button', class: 'btn btn-primary'

app/views/conversations/index.html.slim
.container
  h2 Conversation
  =link_to 'Reload', conversations_path, type: 'button', class: 'btn btn-danger'
  .row
    .col-lg-12
      =render @conversations

app/views/conversations/show.html.slim
.card
  .card-header
    h4 Chatting with &nbsp;
    =@conversation.with(current_user).name
  .card-body
    =render @conversation.personal_messages

=form_for @personal_message do |f|
  .form-group
    =hidden_field_tag 'conversation_id', @conversation.id
  .form-group
    =f.label :body, class: "form-control-label"
    =f.text_area :body, class: 'form-control'
  .form-group
    =f.submit "Send", class: 'btn btn-primary'