config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :admins
  devise_for :users


  resources :users
  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]

  namespace :admin do
    resources :users
    root 'users#index'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'base#index'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'

  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'

  has_many :personal_messages, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  @skip = false

  def skip_notifications!()
    skip_confirmation_notification!
    @skip = true
  end

  def email_changed?
    return false if @skip
    super
  end

  def encrypted_password_changed?
    return false if @skip
    super
  end

  def name
    email.split('@')[0]
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  layout 'layouts/admin_application'

  before_action :find_user, only: %i[edit update destroy]
  before_action :allow_without_password, only: [:update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    # This is hack a new user from Devise gem
    sql = "insert into users (encrypted_password,email, created_at,updated_at) values(
        #{ActiveRecord::Base.connection.quote(user_params[:encrypted_password])},
        #{ActiveRecord::Base.connection.quote(user_params[:email])},now(), now())"
    ActiveRecord::Base.connection.execute(sql)
    redirect_to action: 'index'
  end

  def edit
  end

  def update
    if @user.update!(user_params)
      redirect_to admin_users_path, notice: 'User has updated'
    else
      render @edit, error: "Error #{error_notification}"
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: 'User is destroyed'
  end

  private
    def find_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email,
                                   :encrypted_password,
                                   :reset_password_token,
                                   :reset_password_sent_at,
                                   :remember_created_at,
                                   :sign_in_count,
                                   :current_sign_in_at,
                                   :last_sign_in_at,
                                   :current_sign_in_ip,
                                   :last_sign_in_ip,
                                   :created_at,
                                   :updated_at,
                                   :password,
                                   :password_confirmation)
    end

    def allow_without_password
      if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      else
        @user.encrypted_password.crypt(user_params[:password])
      end
    end
end

app/controllers/users_controller.rb
class UsersController < BaseController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.slim
= simple_form_for [:admin, @user] do |f|
  = f.error_notification
  .form-group
    = f.input :email, label: false, placeholder: 'Email', input_html: { class: 'form-control' }
  .form-group
    = f.input :password, required: true, label: false, placeholder: 'Password', input_html: { class: 'form-control' }
  .form-group
    = f.input :password_confirmation, required: true, label: false, placeholder: 'Password confirmation', input_html: { class: 'form-control' }
  .form-group
    .btn-group role="group" aria-label="buttons"
      = f.submit 'Update User', class: 'btn btn-primary'
      = link_to "Back", admin_users_path, type: 'button', class: 'btn btn-success'

app/views/admin/users/edit.html.slim
.card style="margin: 10px auto;"
  .card-header.bg-warning
    h4 Edit user
  .card-body
    =render 'form'

app/views/admin/users/index.html.slim
table.table.table-striped.table-bordered
  =link_to 'Add new user', new_admin_user_path, type: 'button', class: 'btn btn-primary'
  thead
    tr
      th id
      th Email
      th Created at
      th Action
  tbody
    -@users.each do |user|
      tr
        th scope='row'
          = user.id
        td= user.email
        td= user.created_at
        td
          =link_to 'Edit', edit_admin_user_path(user.id), type: 'button', class: 'btn btn-warning'
          =link_to 'Delete', admin_user_path(user.id), method: :delete, type: 'button', class: 'btn btn-danger'

app/views/admin/users/new.html.slim
.card style="margin: 10px auto;"
  .card-header.bg-primary.text-white
    h4 New user
  .card-body
    =render 'form'