config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :admins
  devise_for :users


  resources :users
  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]

  namespace :admin do
    resources :users
    root 'users#index'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'base#index'
end

app/views/layouts/_admin_menu.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  =link_to "Admin Correspondence System", admin_root_path, class: 'navbar-brand'
  button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
    span.navbar-toggler-icon

  .collapse.navbar-collapse id="navbarSupportedContent"
    ul.navbar-nav.mr-auto
      li.nav-item.active
        =link_to "Home", admin_root_path, class: 'nav-link'
        span.sr-only (current)
      li.nav-item
        =link_to "Users", admin_users_path, class: 'nav-link'

    ul.navbar-nav.md-auto
      -if admin_signed_in?
        li.nav-item
          .nav-link=current_admin.email
        li.nav-item
          =link_to 'Log out', destroy_admin_session_path, method: :delete, class: 'nav-link'
      -else
        li.nav-item
          =link_to 'Sign_in', new_admin_session_path, class: 'nav-link'

app/views/layouts/_menu.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  a.navbar-brand href="#" CorrespondenceSystem
  button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
    span.navbar-toggler-icon

  .collapse.navbar-collapse id="navbarSupportedContent"
    ul.navbar-nav.mr-auto
      li.nav-item.active
        =link_to "Home", root_path, class: 'nav-link'
        span.sr-only (current)
      li.nav-item
        =link_to "Users", users_path, class: 'nav-link'

    ul.navbar-nav.md-auto
      -if user_signed_in?
        li.nav-item
          =link_to current_user.email, user_path(current_user.id), class: 'nav-link'
        li.nav-item
          =link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link'
      -else
        li.nav-item
          =link_to 'Sign_in', new_user_session_path, class: 'nav-link'

app/views/layouts/_messages.html.slim
-flash.each do |key, value|
  .container-fluid
    .row
      .col-sm-12
        .alert.alert-success.alert-dismissible.fade.show role="alert"
          button.close type="button" data-dismiss="alert" aria-label="Close"
            span aria-hidden="true" &times;
          strong=value

app/views/layouts/admin_application.html.slim
doctype html
html
  head
    title TicketsUaTest
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    =render "layouts/admin_menu"
    =render "layouts/messages"
    .container-fluid
      = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title TicketsUaTest
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    =render "layouts/menu"
    =render "layouts/messages"
    .container-fluid
      = yield